// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ColSettting: typeof import('./src/components/common/ProTable/components/ColSettting.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElGroupButton: typeof import('element-plus/es')['ElGroupButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Grid: typeof import('./src/components/common/Grid/index.vue')['default']
    GridItem: typeof import('./src/components/common/Grid/components/GridItem.vue')['default']
    HonourCard: typeof import('./src/components/custom/HonourCard.vue')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    Img: typeof import('./src/components/common/Upload/Img.vue')['default']
    Imgs: typeof import('./src/components/common/Upload/Imgs.vue')['default']
    Pagination: typeof import('./src/components/common/ProTable/components/Pagination.vue')['default']
    ProTable: typeof import('./src/components/common/ProTable/index.vue')['default']
    SearchForm: typeof import('./src/components/common/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./src/components/common/SearchForm/components/SearchFormItem.vue')['default']
    TableColumn: typeof import('./src/components/common/ProTable/components/TableColumn.vue')['default']
  }
}

export { }
